core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('students/', views.StudentList.as_view(), name='students'),
    path('student/<int:pk>', views.StudentDetail.as_view(), name='student'),

    path('student/create', views.StudentCreate.as_view(), name='student_create'),
    path('student/update/<int:pk>', views.StudentUpdate.as_view(), name='student_update'),
    path('student/delete/<int:pk>', views.StudentDelete.as_view(), name='student_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models


class Direction(models.Model):
    name = models.CharField('Название', max_length=255)


class Student(models.Model):
    first_name = models.CharField('Имя', max_length=255, blank=True)
    last_name = models.CharField('Фамилия', max_length=255, blank=True)
    direction = models.ForeignKey(
        Direction,
        on_delete=models.CASCADE,
        verbose_name='Направление',
        blank=True
    )

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

    def __str__(self):
        return self.get_fullname()

    def get_fullname(self) -> str:
        return ' '.join(filter(bool, [self.last_name, self.first_name]))

core/forms.py
from django import forms

from core import models


class StudentForm(forms.ModelForm):
    first_name = forms.CharField(label='Имя', required=True)
    last_name = forms.CharField(label='Фамилия', required=True)
    direction = forms.ModelChoiceField(label='Направление', queryset=models.Direction.objects.all(), required=True)

    class Meta:
        model = models.Student
        fields = '__all__'

core/views.py
from django.urls import reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from core import models, forms


class StudentList(ListView):
    model = models.Student
    template_name = 'core/student_list.html'


class StudentDetail(DetailView):
    model = models.Student
    template_name = 'core/student_detail.html'
    context_object_name = 'student'


class StudentCreate(CreateView):
    model = models.Student
    template_name = 'core/student_create.html'
    form_class = forms.StudentForm

    def get_success_url(self) -> str:
        return reverse('core:students')


class StudentUpdate(UpdateView):
    model = models.Student
    template_name = 'core/student_update.html'
    form_class = forms.StudentForm

    def get_success_url(self) -> str:
        return reverse('core:students')


class StudentDelete(DeleteView):
    model = models.Student
    template_name = 'core/student_delete.html'

    def get_success_url(self) -> str:
        return reverse('core:students')

core/templates/core/student_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Добавление студента</title>
</head>
<body>
    <div class="container">
        <h1 class="display-6">Добавить студента</h1>
        <form action="{% url 'core:student_create' %}" method="POST" class="bg-light p-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Добавить</button>
        </form>
    </div>
</body>
</html>

core/templates/core/student_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Удаление студента №{{ student.pk }}</title>
</head>
<body>
    <div class="container">
        <h1 class="display-6">Удаление студента</h1>
        <form action="{% url 'core:student_delete' object.pk %}" method="POST" class="bg-light p-3">
            {% csrf_token %}
            <p class="h5">Удалить студента {{ student.get_fullname }}?</p>
            {{ form.as_p }}
            <button class="btn btn-danger" type="submit">Удалить</button>
        </form>
    </div>
</body>
</html>

core/templates/core/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Cтудент {{ student.first_name }}</title>
</head>
<body>
    <div class="container">
        <h1 class="display-6">Информация о студенте №{{ student.pk }}</h1>
        <div class="card bg-light p-3">
            <div class="fs-5">Имя: {{ student.first_name }}</div>
            <div class="fs-5">Фамилия: {{ student.last_name }}</div>
            <div class="fs-5">Направление: {{ student.direction.name }}</div>
        </div>
    </div>
</body>
</html>

core/templates/core/student_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Список студентов</title>
</head>
<body>
<a class="btn btn-primary m-2" href="{% url 'core:student_create' %}"> Добавить студента</a>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Имя</th>
        <th scope="col">Фамилия</th>
        <th scope="col">Направление</th>
        <th scope="col">Карточка</th>
        <th scope="col">Обновление</th>
        <th scope="col">Удаление</th>
    </tr>
    </thead>
    {% for student in object_list %}
        <tbody>
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.direction.name }}</td>
            <td><a class="btn text-primary" href="{% url 'core:student' student.pk %}">Открыть</a></td>
            <td><a class="btn text-primary" href="{% url 'core:student_update' student.pk %}">Обновить</a></td>
            <td><a class="btn text-danger" href="{% url 'core:student_delete' student.pk %}">Х</a></td>
        </tr>
        </tbody>
    {% endfor %}
</table>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/student_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Обновление студента</title>
</head>
<body>
    <div class="container">
        <h1 class="display-6">Обновить студента</h1>
        <form action="{% url 'core:student_update' student.pk %}" method="POST" class="bg-light p-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Добавить</button>
        </form>
    </div>
</body>
</html>